name: Generate GH Pages
on:
  # Or on every push as it can change output
  push:
jobs:
  'doc':
    name: 'Update Public documentation'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Setup Python 3 on runner'
        uses: actions/setup-python@v1.2.0
        with:
          python-version: '3.x'
      - name: 'Build mkdocs content to site folder'
        run: |
            pip install -r .github/requirements.txt
            cp -r docker/ docs/
            mkdocs build -f mkdocs.yml
      - name: 'Deploy last version to gh-pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./site