name: Publish NGINX Docker Image
on:
  push:
    branch:
      - master
    paths:
      - docker/nginx/*

jobs:
  NGINX-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: titom73/nginx image build
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: titom73/nginx
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: docker/nginx
        dockerfile: Dockerfile
        tags: "latest"
