name: Publish NGINX Docker Image
on:
  push:
    branch:
      - master
    paths:
      - docker/nginx/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Buster Slim and Default image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: titom73/nginx
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/nginx/Dockerfile
        tags: "latest"
