name: Publish NGINX Docker Image
on:
  push:
    branch:
      - master
    paths:
      - docker/nginx/*
      - .github/workflows/nginx.yml

jobs:
  NGINX-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: nginx image build
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: titom73/nginx
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: docker/nginx
        dockerfile: Dockerfile
        tags: "latest"

    - name: update docker repo description
      uses: peter-evans/dockerhub-description@v2.1.0
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: titom73/nginx
        README_FILEPATH: docker/nginx/README.md